export const movies = [
  {
    adult: false,
    backdrop_path: '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
    genre_ids: [28, 14, 35, 10751, 12, 878],
    id: 675353,
    original_language: 'en',
    original_title: 'Sonic the Hedgehog 2',
    overview:
      'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
    popularity: 6234.63,
    poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
    release_date: '2022-03-30',
    title: 'Sonic the Hedgehog 2',
    video: false,
    vote_average: 7.8,
    vote_count: 1643,
  },
  {
    adult: false,
    backdrop_path: '/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg',
    genre_ids: [28, 12, 14, 53],
    id: 639933,
    original_language: 'en',
    original_title: 'The Northman',
    overview:
      "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
    popularity: 6052.751,
    poster_path: '/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',
    release_date: '2022-04-07',
    title: 'The Northman',
    video: false,
    vote_average: 7.5,
    vote_count: 1119,
  },
  {
    adult: false,
    backdrop_path: '/xHrp2pq73oi9D64xigPjWW1wcz1.jpg',
    genre_ids: [80, 9648, 53],
    id: 414906,
    original_language: 'en',
    original_title: 'The Batman',
    overview:
      'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    popularity: 3914.258,
    poster_path: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    release_date: '2022-03-01',
    title: 'The Batman',
    video: false,
    vote_average: 7.8,
    vote_count: 4795,
  },
  {
    adult: false,
    backdrop_path: '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
    genre_ids: [28, 12],
    id: 335787,
    original_language: 'en',
    original_title: 'Uncharted',
    overview:
      'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
    popularity: 3913.853,
    poster_path: '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
    release_date: '2022-02-10',
    title: 'Uncharted',
    video: false,
    vote_average: 7.2,
    vote_count: 2109,
  },
  {
    adult: false,
    backdrop_path: '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: 'en',
    original_title: 'Spider-Man: No Way Home',
    overview:
      'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
    popularity: 3383.372,
    poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    release_date: '2021-12-15',
    title: 'Spider-Man: No Way Home',
    video: false,
    vote_average: 8.1,
    vote_count: 13030,
  },
];

export const tvShows = [
  {
    backdrop_path: '/1qpUk27LVI9UoTS7S0EixUBj5aR.jpg',
    first_air_date: '2022-03-24',
    genre_ids: [10759, 10765],
    id: 52814,
    name: 'Halo',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Halo',
    overview:
      'Depicting an epic 26th-century conflict between humanity and an alien threat known as the Covenant, the series weaves deeply drawn personal stories with action, adventure and a richly imagined vision of the future.',
    popularity: 3983.731,
    poster_path: '/eO0QV5qJaEngP1Ax9w3eV6bJG2f.jpg',
    vote_average: 8.6,
    vote_count: 791,
  },
  {
    backdrop_path: '/4g5gK5eGWZg8swIZl6eX2AoJp8S.jpg',
    first_air_date: '2003-10-21',
    genre_ids: [18],
    id: 11250,
    name: 'Hidden Passion',
    origin_country: ['CO'],
    original_language: 'es',
    original_name: 'Pasión de gavilanes',
    overview: "The Reyes-Elizondo's idyllic lives are shattered by a murder charge against Eric and León.",
    popularity: 3213.53,
    poster_path: '/lWlsZIsrGVWHtBeoOeLxIKDd9uy.jpg',
    vote_average: 7.6,
    vote_count: 1806,
  },
  {
    backdrop_path: '/vfWdZYGR5505zrCdgTHteFyARu3.jpg',
    first_air_date: '2022-03-30',
    genre_ids: [10759, 10765, 9648],
    id: 92749,
    name: 'Moon Knight',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Moon Knight',
    overview:
      'When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.',
    popularity: 2469.661,
    poster_path: '/YksR65as1ppF2N48TJAh2PLamX.jpg',
    vote_average: 8.2,
    vote_count: 898,
  },
  {
    backdrop_path: '/r9slE8R3rFgDC84VPb10GgPDQUg.jpg',
    first_air_date: '2022-02-14',
    genre_ids: [18, 10766],
    id: 49608,
    name: 'Canım Annem',
    origin_country: ['TR'],
    original_language: 'tr',
    original_name: 'Canım Annem',
    overview: '',
    popularity: 2193.156,
    poster_path: '/pPjyZWvaLzu2MRllG64p6eyQyre.jpg',
    vote_average: 7.3,
    vote_count: 3,
  },
  {
    backdrop_path: '/uu52dx6l1yFN7f60GPhgQFPfOvT.jpg',
    first_air_date: '2018-01-01',
    genre_ids: [10751, 35],
    id: 81772,
    name: 'Oteckovia',
    origin_country: ['SK'],
    original_language: 'sk',
    original_name: 'Oteckovia',
    overview: '',
    popularity: 1885.724,
    poster_path: '/r1hDy1wJ52NEilfcSzs0ocHEJZl.jpg',
    vote_average: 7.7,
    vote_count: 6,
  },
];
